### PR TITLE
Fix leak(#480)

### LINKED ISSUE #480: linktime_composition ASAN LeakSanitizer error
We are working on ASAN errors.
`test_linktime_composition` looks to have several leaks.
They are almost from `class_loader::impl::registerPlugin` but one issue is from `demos/composition/src/linktime_composition.cpp` leak.

## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - build
- Version or commit hash:
  - 77ae4eea17205afb13e3b8ef975a60f3689559ce
- DDS implementation:
  - cyclone_dds
- Client library (if applicable):
  - (NA)

#### Steps to reproduce issue
Build entire ROS2 according to https://github.com/colcon/colcon-sanitizer-reports/blob/master/README.rst.

```
$ colcon test
$ less latest_test/composition/stdout.log

or

$ cd build-asan/composition
$ launch_test test_linktime_composition__rmw_cyclonedds_cpp_Debug.py
```

We got the following log.
The first one, "Direct leak of 144", is from linktime_composition.cpp.
Others are from `class_loader`.

```
2: [test_linktime_composition-1] [INFO] [1610524687.528455323] [linktime_composition]: Load library 
2: [test_linktime_composition-1] [INFO] [1610524687.530394709] [linktime_composition]: Instantiate class rclcpp_components::NodeFactoryTemplate<composition::Client>
2: [test_linktime_composition-1] [INFO] [1610524687.745388818] [linktime_composition]: Instantiate class rclcpp_components::NodeFactoryTemplate<composition::Listener>
2: [test_linktime_composition-1] [INFO] [1610524687.800671413] [linktime_composition]: Instantiate class rclcpp_components::NodeFactoryTemplate<composition::Server>
2: [test_linktime_composition-1] [INFO] [1610524687.841303195] [linktime_composition]: Instantiate class rclcpp_components::NodeFactoryTemplate<composition::Talker>
2: [test_linktime_composition-1] [INFO] [1610524688.881379894] [talker]: Publishing: 'Hello World: 1'
2: [test_linktime_composition-1] [INFO] [1610524688.882102171] [listener]: I heard: [Hello World: 1]
2: [test_linktime_composition-1] [INFO] [1610524689.746876385] [Server]: Incoming request: [a: 2, b: 3]
2: [test_linktime_composition-1] [INFO] [1610524689.748097784] [Client]: Got result: [5]
2: [INFO] [test_linktime_composition-1]: sending signal 'SIGINT' to process[test_linktime_composition-1]
2: [test_linktime_composition-1] [INFO] [1610524689.752167060] [rclcpp]: signal_handler(signal_value=2)
2: [test_linktime_composition-1] 
2: [test_linktime_composition-1] =================================================================
2: [test_linktime_composition-1] ==15440==ERROR: LeakSanitizer: detected memory leaks
2: [test_linktime_composition-1] 
2: [test_linktime_composition-1] Direct leak of 144 byte(s) in 1 object(s) allocated from:
2: [test_linktime_composition-1]     #0 0x7f566d5b8947 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
2: [test_linktime_composition-1]     #1 0x5560b2465afb in main src/ros2/demos/composition/src/linktime_composition.cpp:45
2: [test_linktime_composition-1]     #2 0x7f566c0e20b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
2: [test_linktime_composition-1] 
2: [test_linktime_composition-1] Direct leak of 16 byte(s) in 1 object(s) allocated from:
2: [test_linktime_composition-1]     #0 0x7f566d5b8947 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
2: [test_linktime_composition-1]     #1 0x7f566d110534 in void class_loader::impl::registerPlugin<rclcpp_components::NodeFactoryTemplate<composition::Server>, rclcpp_components::NodeFactory>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) src/ros/class_loader/include/class_loader/class_loader_core.hpp:244
2: [test_linktime_composition-1]     #2 0x7f566d10cfce in ProxyExec0 src/ros2/demos/composition/src/server_component.cpp:53
2: [test_linktime_composition-1]     #3 0x7f566d10e8a9 in __static_initialization_and_destruction_0 src/ros2/demos/composition/src/server_component.cpp:53
2: [test_linktime_composition-1]     #4 0x7f566d10e8c8 in _GLOBAL__sub_I_server_component.cpp src/ros2/demos/composition/src/server_component.cpp:53
2: [test_linktime_composition-1]     #5 0x7f566df07b89  (/lib64/ld-linux-x86-64.so.2+0x11b89)

(snip, totally 4 leaks related with class_loader)
```

#### Expected behavior
no leak

#### Actual behavior
leaks, see above.

### PR DESCRIPTION
**Pull request by y-okumura-isp**
Fix #480.
Although there are ASAN errors related to class_loader, this PR reduces one error.

Signed-off-by: y-okumura-isp <y-okumura@isp.co.jp>

### CODE REVIEW

File: composition/src/linktime_composition.cpp [hunk 1]
```diff
@@ -32,7 +32,7 @@ int main(int argc, char * argv[])
   rclcpp::Logger logger = rclcpp::get_logger(LINKTIME_COMPOSITION_LOGGER_NAME);
   rclcpp::executors::SingleThreadedExecutor exec;
   rclcpp::NodeOptions options;
-  std::vector<class_loader::ClassLoader *> loaders;
+  std::vector<std::shared_ptr<class_loader::ClassLoader>> loaders;
```
Comment (clalancette) [inline composition/src/linktime_composition.cpp:35]: Since there is only ever going to be one owner, I would suggest using a `std::unique_ptr` here.

**Review by clalancette — CHANGES_REQUESTED** [review]
One nit, and then I'm happy to approve and run CI.

**Comment by y-okumura-isp** [comment]
Thank you for comment.
Sorry for late reply as I studied why we should have loaders.

http://wiki.ros.org/class_loader may be the reason.

> 2.5 Understanding Loading and Unloading
> if I create an object from a class defined within a runtime library, I then unload the library, and then I try to use the object...things will go bad.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13448/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8359/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11171/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13502/)

**Comment by clalancette** [comment]
Windows CI is failing for a completely unrelated reason.  I think this is safe enough to put it without that, so I'm going to go ahead and merge.
