### PR TITLE
check that resolution is at least as big as burger

### LINKED ISSUE #254: cam2image crashes when specifying -x -y and -b
## Bug report

**Required Info:**

- Operating System:
  - Windows 10
- Installation type:
  - binaries
- Version or commit hash:
  - https://ci.ros2.org/view/packaging/job/packaging_windows/1042/
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

```
ros2 run image_tools cam2image -b -x 16 -y 16
```

#### Expected behavior
Either a smaller image would be published or a message would be printed saying resizing the generated image is not supported.

#### Actual behavior
```
>ros2 run image_tools cam2image -b -x 16 -y 16
[INFO] [cam2image]: Publishing data on topic 'image'
OpenCV(3.4.1) Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in cv::Mat::Mat, file C:\Users\osrf\opencv3-build\opencv\modules\core\src\matrix.cpp, line 464
```

#### Additional information

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fixes #254.

The first check ensures that the resolution is at least big enough to contain the burger template.

Additionally the initialization avoids a division by zero and the "bouncing" sacrifices "accuracy" over staying in bound in very constraint sizes.

### CODE REVIEW

File: image_tools/src/burger.cpp [hunk 1]
```diff
@@ -122,11 +135,19 @@ cv::Mat & Burger::render_burger(size_t width, size_t height)
     // bounce as needed
     if (x[b] < 0 || x[b] > width_i - burger_template.size().width - 1) {
       x_inc[b] *= -1;
-      x[b] += 2 * x_inc[b];
+      if (x[b] < 0) {
+        x[b] = 0;
+      } else {
+        x[b] = width_i - burger_template.size().width;
```
Comment (sloretz) [inline image_tools/src/burger.cpp]: Looks like `x_inc[b]` is unused?

Comment (dirk-thomas) [reply image_tools/src/burger.cpp]: Correct it just truncates the movement at the border. It had already been moved in line 133.
